{{ define "title" }}Terms Of Service and privacy policy{{ end }}

{{ define "content" }}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            Terms of Service<br>
            <br>
            Table of contents<br>
            1. Introduction<br>
            2. Installation & registration<br>
            3. Account information<br>
            4. Safety<br>
            5. Content<br>
            6. Payment and refund policy<br>
            7. Privacy Policy<br>
            8. Cheating<br>
            9. Toxic behaviour:<br>
            <br>
            Applicable Terms<br>
            The following terms refer to the Android Application (Hackers - Hacking simulator) found on Google Play Store:<br>
            - the application (app)<br>
            - the game<br>
            The following terms refer to the backend of the game:<br>
            - the servers / service<br>
            <br>
            The following terms refer to the whole system that the game is consisting of:<br>
            - the service<br>
            <Br>
            The terms "we" or "us" or "developer" or "developers" refer to one or more of the following: the developer(s), the owner(s), the moderator(s), and/or the staff.<br>
            Note: Ownership lies with the “owner(s).” No other party listed has or posses ownership except by formal documentation.<br>
            <br>
            The terms “BlackBit(s)” or “BB(s)” and “HackCoin(s)” or “HC” are referred to as the in-game-currency. and might be changed prior to the full relese.<br>
            <br>
            <br>
            Please read carefully. By Installing, playing, or using this app, you agree to the following terms and conditions set forth herein. If you do not understand or do not accept any part of the terms or conditions, then you must not use the game or any other product or service offered by the owner(s).
            <br><br>
            1. Introduction<br>
            Thanks for playing "Hackers". This is a Massive Multiplayer Online game (MMO). All tools, theory, and hacking simulations are believed to be fiction (Not Real) and do not apply to real hacking except for certain terminology. We do not condone hacking, cracking, phreaking, stealing, or any other illegal activities. If any one entity, person, place, and/or thing is caught in or discussing illegal activities, YOU WILL BE REPORTED TO THE YOUR LOCAL AUTHORITIES.
            <br>
            2. Installation and Registration:<br>
            The game has no usual "registration" form; once you enter a user name and a password, you are registered. If someone else has already registered with that usename, you will be notified of an already-used-username or wrong password.<br>
            For the previous reason, account deletion is NOT POSSIBLE. However, if you do not login to the game for 3 days, your account wil start losing points. Once you hit -1 points in the game, a timer of 14 days will start counting down. On day 0 your account and all game play will be permanently deleted. Permanent account deletion may occur between 14 days to 2 years depending on the player level.<br>
            Please note that if you login again, your account will be recreated, so DO NOT CHECK if your account has been deleted by registering or logging in again.<br>
            <br>
            3. Account information:<br>
            - We do not save any information about you except the username and a one-way-encrypted (hashed, can't be reversed) password you choose while registering/logging in.<br>
            By registering, you agree that the username and/or password has no sensitive data, or data that you do not want shown publicly, as the username will be displayed in the game for other players either in the chat rooms or by any other means. The password, however, is encrypted and hashed and is not known by anyone, even us.<br>
            - Because the password is hashed and encrypted, it is impossible for us to remind you of your password or know your password. We will not share your data with anyone; upon any simple request.<br>
            - We save a Google "FireBase Token" generated by Google service for push notifications. This token is automatically changed by Google on periods of time unknown to us, and it is deleted/revoked by Google once the app has been uninstalled. You agree not to ask us for this token, or ask us to delete this token from our systems as it is encrypted and not searchable.<br>
            - We do not delete accounts by request.<br>
            - Your account on the website and/or game or your access to the service(if users can’t have an account with you) can be terminated in case of abuses or at our sole discretion.<br><Br>
            - Registering with improper name will result in a permanent ban from the system, and might result in losing access to your account. Improper names include all names that do not match our rules (Found on public forum.hackerz.online) and/or any name the the staff finds improper.<Br>
            <br>
            4. Safety:<br>
            - The public chat in the game is moderated and has rules which are displayed for all new players, and is easily shown for anyone who types "/rules" in the chat. Moderators and administration have the right to warn, ban, and block any player at any time for breaking the rules, or for any other reason that they deem necessary.<br>
            - This game/app has been designed for entertainment purposes, is not and never was intended for any real hacking purpose, thus any real-hacking related topics are discouraged. It is the right of the game administratior(s) and moderator(s) to ban any player for breaking this rule without a warning.<br>
            - The game is designed for best intentions in mind, However we are not liable and do not warranty any damage(s) that may occur from the game directly and/or indirectly; to include, but not limited to, physical, psychological, emotional, monetary, and/or one’s property. The service is provided “as is.”<br>
            - Please do not play the game or use the mobile phone or tablet while driving or operating anything. We are not responsible for any kind of damage caused by playing this game directly or indirectly<br>
            - The system is monitored 24/7 by word filtering and speech analysers. Trying to use the service for any illegal purposes will result in your data (email/IP/chat/anything you did in the game) to be sent to the legal authorities in your country.)<br>
            - Using TOR proxy is prohibited due to some technical and ethical reasons.<Br>
            - Using of VPNs is discouraged and might result in losing your account.<Br>
            <br>
            5. Content:<br>
            - The owner(s) of the app posses all trademarks and copyrights for all content generated by the users in the game, so by chatting, creating missions, creating and/or uploading anything to the game. By agreeing you grant the full copyright and ownership of generated content to the owner(s) of the app.<br>
            <br>
            Beta version of the app. That means this game is still UNDER DEVELOPMENT, and it is listed as well in the play store. By installing it, you agree that you expect an unstable service, crashing software, and unfinished features.<br>
            <br>
            6. Payment and refund policy:<br>
            - You buy the game currency (BBs / BlackBits) with real money, no refund for any used BBs, no refund for BBs you got by other means (luck in the game, daily packages, etc...) and no refund will be given for BBs left after use.<br>
            - Reversing a payment will result in banning your account from chat automatically by the system, taking the BBs you purchased and removing 50% of your reputation points. In case there were not enough BBs for the refund, you will lose access to your account. This is irreversible, and no exceptions.<br>
            - If there is an issue with the payment, send us an email and we will fix the issue. Example:  Reversing payment because of technical reason(s) such as not receiving purchase. (Proof of payment will be required.).<br>
            <br>
            7. Privacy Policy:<br>
            - We do not store anything except your username, hashed password, and any content you create in the system.<br>
            - We will not share your hashed password to anyone. Your hashed password can't be un-hashed or decrypted, so even we will not know it.<br>
            - We will know your IP address while you are online but we do not commonly store it, however read the security section above.<br>
            - All content that you have written including your username will at some point be available for anyone online through the game in the form of chat text, missions text, or your username showing in various places in the game. Thus, do not post anything you dont want people to see in public.<br>
            - We do not collect any private information from your device at all.<br>
            <br>
            8. Cheating:<br>
            - Using of bots and/or macros is prohibited. any automated game-play will have your account reputation reset, or your account permanently deleted wihtout any warning.<br>
            - Discovering any exploit in the game and not reporting it immediately will result in deletion of your account without any warning.<br>
            <br>
            9. Toxic behaviour:<br>
            - Toxic behaviour and racism will result in banning you from the chat room temporarily or permanently, and might result in losing access to your account.<br>
            - Any attempt to scare the players or steer them away from the game will NOT be tolerated.<br>
            - Any attempt to spam, scam and/or phish the players will not be tolerated.<br>
            - The moderators have the right to ban you from the chat as they see fit. The chat room have rules which you must follow.<br>
            <br>
            Rules, Terms and Conditions, Terms of Service, and EULA are subject to change at any time with or without notice.
            <br>



        </div>
    </div>
</div>
{{ end }}

{{ define "footer" }}{{ end }}

{{ define "post_js" }}{{ end }}