{{ define "title" }}Terms of Service/EULA{{ end }}

{{ define "content" }}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            Terms of Service<br>
            <br>
            Table of Contents<br>
            1. Introduction<br>
            2. Advertising<br>
            3. Installation and Registration<br>
            4. Account Information<br>
            5. Safety<br>
            6. Content<br>
            7. Payment and Refund Policy<br>
            8. Privacy Policy<br>
            9. Cheating<br>
            10. Toxic Behavior<br>
            11. Agreement<br>
            <br>
            Applicable Terms<br>
            The following terms refer to the Android Application (Hackers - Hacking simulator) found on Google Play Store:<br>
            - the game<br>
            - the application (app)<br>
            - the servers<br>
            The following terms refer to the backend of the game:<br>
            - the servers / service<br>
            <br>
            The following terms refer to the whole system that the game is consisting of:<br>
            - the service<br>
            <Br>
            The terms "we" or "us" or "developer" or "developers" refer to one or more of the following: the developer(s), the owner(s), the moderator(s), and/or the staff.<br>
            Note: Ownership lies with the “owner(s).” No other party listed has or posses ownership except by formal documentation.<br>
            <br>
            The terms “BlackBit(s)” or “BB(s)” and “HackCoin(s)” or “HC” are referred to as the in-game-currency. and might be changed with or without prior notice<br>
            <br>
            <br>
            Please read carefully. By Installing, playing, or using this app, you agree to the following terms and conditions set forth herein. If you do not understand or do not accept any part of the terms or conditions, then you must not use the game or any other product or service offered by the owner(s).
            <br><br>
            1. Introduction<br>
            Thanks for playing "Hackers". This is a Massive Multiplayer Online game (MMO). All tools, theory, and hacking simulations are believed to be fiction (Not Real) and do not apply to real hacking except for certain terminology. We do not condone hacking, cracking, phreaking, stealing, or any other illegal activities. If any one entity, person, place, and/or thing is caught in or discussing illegal activities, YOU WILL BE REPORTED TO THE YOUR LOCAL AUTHORITIES, and/or lose access to your account.
            <br>
            2.Advertising:<br>
            You cannot and will not advertise/post/display any content WITHOUT the owner(s) consent. No one EXCEPT the owner can authorize this. If you do gain permission to advertise, do not spam the content. Your permission can be revoked at any time for whatever reason.<br>
            <br>
            3. Installation and Registration:<br>
            The game has no usual "registration" form; once you enter a user name and a password, you are registered. If someone else has already registered with that usename, you will be notified of an already-used-username or wrong password.<br>
            For the previous reason, account deletion is NOT POSSIBLE. However, if you do not login to the game for 3 days, your account wil start losing points. Once you hit -1 points in the game, a timer of 14 days will start counting down. On day 0 your account and all game play will be permanently deleted. Permanent account deletion may occur between 14 days to 2 years depending on the player level.<br>
            Please note that if you login again, your account will be recreated, so DO NOT CHECK if your account has been deleted by registering or logging in again.<br>
            <br>
            4. Account information:<br>
            - We do save information that you provide, to include but not limited to your, username, a one-way-encrypted (hashed, can't be reversed) password you choose while registering/logging in, IP Address, and email.<br>
            - Your email is used to identify the game progress, Your IP is checked for determining what country-specific-chat-room to open for you.<br>
            - By registering, you agree that the username and/or password has no sensitive data, or data that you do not want shown publicly, as the username will be displayed in the game for other players either in the chat rooms or by any other means. The password, however, is encrypted and hashed and is not known by anyone, even us.<br>
            - Because the password is hashed and encrypted, it is impossible for us to remind you of your password or know your password. We will not share your data with anyone; upon any simple request.<br>
            - We save a Google "FireBase Token" generated by Google service for push notifications. This token is automatically changed by Google on periods of time unknown to us, and it is deleted/revoked by Google once the app has been uninstalled. You agree not to ask us for this token, or ask us to delete this token from our systems as it is encrypted and not searchable. and does not include any private information.<br>
            - Accounts can be deleted by request. Simply write send us a message from the same email address that is used to register in the game <br>
            - Your account on the website, forums, game, and/or your access to any service that Okitoo Networks provides can be terminated in cases of abuse or at our sole discretion.(Users cannot share accounts.)<br><br>
            - Registering with an improper (username that contains obscenities or illegal activities) username will result in a permanent ban from the system, and might result in losing access to your account.<br>
            <br>
            5. Safety:<br>
            - Children under the age of eighteen (18) years of age must gain parental consent before registering for the game and when requested for proof, will present the staff adequate proof of parental consent at any time they may deem necessary in accordance with COPPA.<br>
            - COPPA Sources (as applicable): 15 U.S.C. Ch. 91 Subsection 6501, 15 U.S.C. Ch. 91 Subsection 6502. If parental consent cannot be provided, your account may be suspended and/or terminated at any time with/without notice.<br>
            - The public chat in the game is moderated and has rules which are displayed for all new players, and is easily shown for anyone who types "/rules" in the chat. Moderators and administration have the right to warn, ban, and block any player at any time for breaking the rules, or for any other reason that they deem necessary.<br>
            - This game/app has been designed for entertainment purposes, is not and never was intended for any real hacking purpose, thus any real-hacking related topics are discouraged. It is the right of the game administrator(s) and moderator(s) to ban any player for breaking this rule without a warning.<br>
            - The game is designed for best intentions in mind, However we are not liable and do not warranty any damage(s) that may occur from the game directly and/or indirectly; to include, but not limited to, physical, psychological, emotional, monetary, and/or one’s property. The service is provided “as is.”<br>
            - We are not liable and do not warranty any damage(s) that may occur from the game directly and/or indirectly; to include, but not limited to, physical, psychological, emotional, monetary, and/or one’s property. The service is provided “as is.”<br>
            - Please do not play the game or use the mobile phone or tablet while driving or operating anything. We are not responsible for any kind of damage caused by playing this game directly or indirectly<br>
            - The system is monitored 24/7 by word filtering and speech analysers. Trying to use the service for any illegal purposes will result in your data (email/IP/chat/anything you did in the game) to be sent to the legal authorities in your country.)<br>
            - Using TOR proxy is prohibited due to some technical and ethical reasons.<br>
            - Using of VPNs is discouraged and might result in losing access your account, or be permanently banned from communicating with other players.<br>
            <br>
            6. Content:<br>
            - The owner(s) of the app posses all trademarks and copyrights for all content generated by the users in the game, content including but not limited to: your game progress, chat messages and messages, files created in the games' "file manager", missions created by users, creating and/or uploading anything to the game. By agreeing you grant the full copyright and ownership of generated content to the owner(s) of the app.<br>
            <br>
            - This is game is in its alpha/beta version. That means this game is still UNDER DEVELOPMENT and it is listed as well in the play store. By installing it, you agree that you expect an unstable service, crashing software, unfinished features, possible loss of information, content, purchases, and/or any other data.<br>
            <br>
            7. Payment and Refund Policy:<br>
            - All purchases will be made through the Google Play Store. Cash, Check, Credit Card, Money Order, or other means of payment directly to the owner(s), administrator(s), moderator(s) and/or contractor(s) is strictly FORBIDDEN. Anyone who asks you for payment directly must be reported to the developer IMMEDIATELY.<br>
            - If for any reason there are exigent circumstances to an order, you can provide proof(s) of purchase to the hackerz.online staff through PRIVATE means of communication.<br>
            - If you purchase the game currency (BB’s / BlackBit’s) with real money, there are no refund(s) and/or trades for:<br>
            • any used BB’s,<br>
            • BB’s you received by other means (luck in the game, daily packages, etc...),<br>
            • BBs left after use,<br>
            • Items (anything purchased within the game) purchased with BB’s, real money, currency, and/or other means,<br>
            • items lost during regular game play,<br>
            • items lost during scheduled or unscheduled server maintenance, failures, resets, and/or changes.<br>
            - Reversing a payment will result in banning your account from chat automatically by the system. This will result in taking the BB’s you purchased and removing 50% of your reputation points. In case there were not enough BB’s for the refund, you will lose access to your account. This is irreversible, and no exceptions.<br>
            - If there is an issue with the payment, please feel free to send us an email at developer@m.hackerz.online and/or support@m.hackerz.online and we will fix the issue. Example: Reversing payment because of technical reason(s) such as not receiving purchase. (Proof of payment is required, forwarding the receipt sent to your email by from play-store is accepted but not screenshots.)<br>
            <br>
            8. Privacy Policy:<br>
            - We do securely store your username, hashed password, content you create, your IP address, and email. We will not share your information with third party advertiser's or anyone else without your consent, a legal warrant, you violate the terms of service, and/or the terms and conditions!<br>
            - We will never give your email address to any third party, except if required by legal authorities with a legal warrant. Email however might be visible to our support team for verification purpose and or support requests.<br>
            - We do not practice spamming, however we might send no more than 1 email per half year after the initial "Email Verification" email (which not might be sent).<br>
            - Some or all of the information that you provide us via account profile and/or connection can be viewed and/or recorded for security and/or compliance purposes.<br>
            - We will not share your hashed password to anyone. Your hashed password can't be un-hashed or decrypted.<br>
            - All content that you have written including your username will at some point be available for anyone online through the game in the form of chat text, mission’s text, or your username showing in various places in the game. Thus, do not post anything you do not want people to see in public.<br>
            - We do not collect any private information from your device, at all.<br>
            <br>
            9. Cheating:<br>
            - Using of bots and/or macros is prohibited. any automated game-play will have your account reputation reset, or your account permanently deleted without any warning.<br>
            - Discovering any exploit in the game and not reporting it immediately will result in deletion of your account without any warning.<br>
            <br>
            10. Toxic behavior:<br>
            - Toxic behavior, including but not limited, racism, discrimination, bullying, cyber bullying, sexism, stereotyping, profanity, harassment, and or anything that is considered to criminal or rude/demeaning in nature will result in banning you from the chat room temporarily, permanently, result in lose of access to your account, and/or the possibility of your information being reported to your federal, state, municipal, and/or local authorities.<br>
            - Any attempt to scare the players or steer them away from the game will NOT be tolerated.<br>
            - Any attempt to spam, scam, and/or phish the players will NOT be tolerated.<br>
            - Any attempt to conduct and/or stimulate illegal activities will NOT be tolerated.<br>
            <br>
            11. Agreement:<br>
            - By registering for the content that Okitoo Networks and Hackerz.Online provides to you, you contractually agree to these terms set before you and any changes herein forth.<br>
            - If (at anytime) you wish to exit this agreement, you must deactivate your account(s) via your user settings. (Note that deactivation does not delete all of the content that you have already provided except your personal information, unless your account is under review for security purposes.)<br>
            <br>
            Rules, Terms and Conditions, Terms of Service, and EULA are subject to change at any time with or without notice.
            <br>



        </div>
    </div>
</div>
{{ end }}

{{ define "footer" }}{{ end }}

{{ define "post_js" }}{{ end }}
